openapi: 3.1.0
info:
  title: PROFNIT Apostilas
  description: Base de textos das apostilas do PROFNIT em JSON estático hospedado no GitHub Pages.
  version: "1.0.0"
servers:
  - url: https://WellingtonValente.github.io/profnit-schema
paths:
  /profnit_apostilas.json:
    get:
      summary: Lista as apostilas do PROFNIT
      operationId: listarApostilas
      responses:
        '200':
          description: JSON com todas as apostilas
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    titulo:
                      type: string
                    arquivo:
                      type: string
                    texto:
                      type: string
